apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    env: dev
    managed-by: terraform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    env: monitoring
    managed-by: terraform

